# hockey
Import('env shared')
env = env.Clone(CPPPATH='#src/shared')
env.HeaderTmpl('hockey')
env.GLSL('shaders')
SHARED = map(lambda x: shared[x], ['gl', 'logging', 'subproc', 'share'])
exe = env.Program('hockey', ['server.c', 'vec2.c']+SHARED, LIBS=['GLESv2', 'glfw', 'm'])

env.Install('#bin', exe)
env.Install('#include', 'hockey.h')


