#shared
print(Platform())
Import('env')
env = env.Clone()

src = ['util.c', 'glhelper.c', 'window_glfw.c']
if Platform().name == 'win32':
	src += ['subproc_w.c', 'share_mem_w.c']
else:
	src += ['subproc.c', 'share.c']
	
print(src)

shared_utils = env.Library('shared_utils', src)

Return('shared_utils')
