NAME="pong"
Import("*")
if 'env' not in globals():
	env = Environment()
env.Append(LIBS=['m'], CPPPATH=['#include'])
prog = env.Program(NAME, ['main.c', 'vec2.c'])
env.Depends(prog, File('#include/pixie.h'))
inst = env.Install('#bin', prog)
