NAME="hello"
Import("*")
if 'env' not in globals():
	env = Environment()
env.Append(CPPPATH=['#include'])
prog = env.Program(NAME, ['main.c'])
env.Depends(prog, File('#include/pixie.h'))
inst = env.Install('#bin', prog)
